version: '3.7'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: ${PROJECT_NAME}-server
    env_file:
      - ./.env
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: ${PROJECT_NAME}-mongo-db
    env_file:
      - ./.env
    volumes:
      - mongo-db-vol:/data/db

volumes:
  mongo-db-vol:
