version: '3.7'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    container_name: ${PROJECT_NAME}-client
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: ${PROJECT_NAME}-server
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: ${PROJECT_NAME}-mongo-db
    env_file:
      - ./.env
    volumes:
      - mongo-db-vol:/data/db

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    container_name: ${PROJECT_NAME}-nginx
    env_file:
      - ./.env
    depends_on:
      - server
      - client
    restart: always
    

volumes:
  mongo-db-vol:
